In [2]:
from lxml import etree
import pandas as pd
from collections import Counter
import os
import glob
import re
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter
from numpy import array
import numpy as np


wdir = "/home/jose/Dropbox/biblia/tb/"
file = "TEIBible" # "*.xml"
outdir = "/home/jose/Dropbox/biblia/tb/resulting data/"

In [3]:
entities = pd.ExcelFile(wdir + "entities.xls",  index_col=0).parse('Sheet1').fillna("")

In [4]:
entities.head(3)

,id,NormalizedName-sp,aclaration,variants,comments,book,cert,Gender,NormalizedName-ge,NormalizedName-po,...,PHM,HEB,JAM,1PE,2PE,1JO,2JO,3JO,JUD,REV
0.0,#per0,persona no definida,,,,NT,,none,nicht identifizierte Person,pessoa não identificada,...,0,0,0,0,0,0,0,0,0,0
1.0,#per1,Jesús,,,,NT,,male,Jesus,Jesus,...,13,75,5,34,24,48,7,0,8,102
2.0,#per2,Abraham,,Abram,,AT,,male,Abraham,Abraão,...,0,13,4,2,0,0,0,0,0,0

In [5]:
secure_places = entities.loc[ (entities["type"]== "place" ) & (entities["latitude"]!="" ) & (entities["longitude"]!="") & (entities["geo_cert"].isin(["high","medium"]))]
secure_places.shape

(142, 75)

In [6]:
secure_places.head(3)

,id,NormalizedName-sp,aclaration,variants,comments,book,cert,Gender,NormalizedName-ge,NormalizedName-po,...,PHM,HEB,JAM,1PE,2PE,1JO,2JO,3JO,JUD,REV
1881.0,#pla1,Belén,,,,,,,Bethlehem,Belem,...,0,0,0,0,0,0,0,0,0,0
1882.0,#pla2,Judea,,Judá,Es lo mismo que Judá?,,,,Judäa,Judeia,...,0,2,0,0,0,0,0,0,0,0
1883.0,#pla3,Jerusalén,,,Ciudad de David? Llamada Aholiba en EZE 23,,,,Jerusalem,Jerusalem,...,0,0,0,0,0,0,0,0,0,4

In [7]:
books = pd.ExcelFile(wdir + "documentation/books.xlsx",  index_col=0).parse('Sheet1').fillna("")

In [8]:
books.head(3)

,bible,id,libro,testamento,hecho,english,codebook,Chapters,Genre
0,bible,1,Génesis,antiguo,1,Genesis,GEN,50.0,historical
1,bible,2,Éxodo,antiguo,1,Exodus,EXO,40.0,historical
2,bible,3,Levítico,antiguo,1,Leviticus,LEV,27.0,law

In [9]:
parser = etree.XMLParser(encoding='utf-8')

In [10]:
documento_xml = etree.parse(wdir+file+".xml", parser)

In [11]:
documento_root = documento_xml.getroot()

In [12]:
namespaces_concretos = {'tei':'http://www.tei-c.org/ns/1.0','xi':'http://www.w3.org/2001/XInclude'}

In [13]:
books["latitude"] = ""
books["longitude"] = ""

for book in documento_root.xpath('//tei:TEI', namespaces=namespaces_concretos, with_tail=True):
    title = book.xpath('.//tei:title[2]/tei:idno[@type="string"]/text()', namespaces=namespaces_concretos, with_tail=True)[0]
    rss = book.xpath('.//tei:rs[not(@cert)]/@key|.//tei:rs[@cert="medium"]/@key', namespaces=namespaces_concretos, with_tail=True)
    set_entities = list(set([entity for reference in rss for entity in reference.split(" ")]))
    print(title)
    print(len(rss))
    print(len(set_entities))

    longitude = secure_places.loc[secure_places["id"].isin(set_entities)]["longitude"].mean()
    latitude = secure_places.loc[secure_places["id"].isin(set_entities)]["latitude"].mean()
    
    books.loc[books["codebook"]==title, ["longitude"]] = longitude
    
    books.loc[books["codebook"]==title, ["latitude"]] = latitude
    print(longitude, latitude)

GEN
4962
494
36.79308342903226 32.615686745161284
EXO
3028
162
33.7367165076923 30.3698383
LEV
1652
56
34.112561 30.521765400000003
JOS
3288
513
34.990373285245916 31.70407139344263
JDG
2645
295
35.46787480943398 31.72956351698113
RUT
306
37
33.61885083333333 29.8573287
1SA
3449
232
35.04616101176471 31.598014517647055
2SA
3239
298
35.26103851874999 32.218329237499994
EZR
1509
333
37.691306715 32.320034525000004
NEH
1701
412
37.03201238064516 31.317099551612905
JOB
905
56
38.364043499999994 19.865082
PSA
3502
148
35.43785641612905 30.9268848483871
ECC
259
22
35.228163 32.00034566666667
LAM
281
30
35.19855448 31.71697948
JER
5120
314
35.543290773076926 32.18487479807693
EZE
3029
214
35.465907730000005 31.595325427999995
DAN
1002
82
37.0924016 29.885824728571432
HOS
505
87
35.25010343333333 31.981634866666663
JOE
193
40
33.22362268181818 31.819257490909095
AMO
463
98
35.05031269166667 31.806583025000005
OBA
81
31
35.208343622222216 31.60977827777778
JON
113
13
34.92986376666667 36.65253283333333
MIC
293
68
36.315512038461534 32.03090073076924
NAH
74
29
33.51317685 30.024997480000003
HAB
88
24
35.749305 31.873600000000007
ZEP
175
48
35.38185618999999 30.59335771
HAG
144
18
34.1192041 30.7391216
ZEC
609
109
34.6678293 32.48267576153847
MAL
160
35
34.9578466 31.2363364
MAT
1498
180
35.06979411538461 32.3827941576923
MAR
1118
133
34.659927631578945 32.29664650000001
LUK
321
62
35.69118726666667 32.56743606666667
JOH
1498
100
35.38563382142858 32.05738786428572
ACT
2662
309
30.489004375862077 34.1376530137931
ROM
814
98
22.626880316666668 36.448778483333335
1CO
764
67
31.59657838888889 33.64801911111111
2CO
363
42
29.44019285555556 35.895230811111105
GAL
306
52
37.2690598 31.027710200000005
PHI
169
29
26.5137687 37.7649163
1TI
202
29
24.556665099999996 39.77852525
2TI
144
54
27.432393722222223 38.83026567777778
TIT
87
25
24.8092691 35.240117
PHM
50
15
nan nan
HEB
495
78
31.628480099999997 30.469013885714286
JAM
91
17
nan nan
1PE
184
36
39.279109500000004 36.0484985
2PE
113
32
nan nan
1JO
249
18
nan nan
2JO
23
7
nan nan
3JO
21
8
nan nan
JUD
65
24
30.802497999999996 26.820553000000004
REV
703
84
33.358925400000004 34.97476635454546

In [16]:
books

,bible,id,libro,testamento,hecho,english,codebook,Chapters,Genre,longitude,latitude
0,bible,1,Génesis,antiguo,1,Genesis,GEN,50.000000,historical,36.7931,32.6157
1,bible,2,Éxodo,antiguo,1,Exodus,EXO,40.000000,historical,33.7367,30.3698
2,bible,3,Levítico,antiguo,1,Leviticus,LEV,27.000000,law,34.1126,30.5218
3,bible,4,Números,antiguo,0,Numbers,NUM,36.000000,law,,
4,bible,5,Deuteronomio,antiguo,0,Deuteronomy,DEU,34.000000,law,,
5,bible,6,Josué,antiguo,1,Joshua,JOS,24.000000,historical,34.9904,31.7041
6,bible,7,Jueces,antiguo,1,Judges,JDG,21.000000,historical,35.4679,31.7296
7,bible,8,Rut,antiguo,1,Ruth,RUT,4.000000,historical,33.6189,29.8573
8,bible,9,1 Samuel,antiguo,1,1 Samuel,1SA,31.000000,historical,35.0462,31.598
9,bible,10,2 Samuel,antiguo,1,2 Samuel,2SA,24.000000,historical,35.261,32.2183
10,bible,11,1 Reyes,antiguo,*,1 Kings,1KI,22.000000,historical,,
11,bible,12,2 Reyes,antiguo,0,2 Kings,2KI,25.000000,historical,,
12,bible,13,1 Crónicas,antiguo,0,1 Chronicles,1CH,29.000000,historical,,
13,bible,14,2 Crónicas,antiguo,0,2 Chronicles,2CH,36.000000,historical,,
14,bible,15,Esdras,antiguo,1,Ezra,EZR,10.000000,historical,37.6913,32.32
15,bible,16,Nehemías,antiguo,1,Nehemiah,NEH,13.000000,historical,37.032,31.3171
16,bible,17,Ester,antiguo,0,Esther,EST,10.000000,historical,,
17,bible,18,Job,antiguo,1,Job,JOB,42.000000,wisdom,38.364,19.8651
18,bible,19,Salmos,antiguo,1,Psalms,PSA,150.000000,lyric,35.4379,30.9269
19,bible,20,Proverbios,antiguo,0,Proverbs,PRO,31.000000,wisdom,,
20,bible,21,Eclesiastés,antiguo,1,Ecclesiastes,ECC,12.000000,wisdom,35.2282,32.0003
21,bible,22,Cantares,antiguo,0,Song of Solomon,SON,8.000000,lyric,,
22,bible,23,Isaías,antiguo,0,Isaiah,ISA,66.000000,apocalyptic,,
23,bible,24,Jeremías,antiguo,1,Jeremiah,JER,52.000000,prophecy,35.5433,32.1849
24,bible,25,Lamentaciones,antiguo,1,Lamentations,LAM,5.000000,lyric,35.1986,31.717
25,bible,26,Ezequiel,antiguo,1,Ezekiel,EZE,48.000000,prophecy,35.4659,31.5953
26,bible,27,Daniel,antiguo,1,Daniel,DAN,12.000000,prophecy,37.0924,29.8858
27,bible,28,Oseas,antiguo,1,Hosea,HOS,14.000000,prophecy,35.2501,31.9816
28,bible,29,Joel,antiguo,1,Joel,JOE,3.000000,prophecy,33.2236,31.8193
29,bible,30,Amós,antiguo,1,Amos,AMO,9.000000,prophecy,35.0503,31.8066
...,...,...,...,...,...,...,...,...,...,...,...
40,bible,41,Marcos,nuevo,1,Mark,MAR,16.000000,Gospel,34.6599,32.2966
41,bible,42,Lucas,nuevo,0,Luke,LUK,24.000000,Gospel,35.6912,32.5674
42,bible,43,Juan,nuevo,1,John,JOH,21.000000,Gospel,35.3856,32.0574
43,bible,44,Hechos,nuevo,1,Acts,ACT,28.000000,Gospel,30.489,34.1377
44,bible,45,Romanos,nuevo,1,Romans,ROM,16.000000,letter,22.6269,36.4488
45,bible,46,1 Corintios,nuevo,1,1 Corinthians,1CO,16.000000,letter,31.5966,33.648
46,bible,47,2 Corintios,nuevo,1,2 Corinthians,2CO,13.000000,letter,29.4402,35.8952
47,bible,48,Gálatas,nuevo,1,Galatians,GAL,6.000000,letter,37.2691,31.0277
48,bible,49,Efesios,nuevo,0,Ephesians,EPH,6.000000,letter,,
49,bible,50,Filipenses,nuevo,1,Philippians,PHI,4.000000,letter,26.5138,37.7649
50,bible,51,Colosenses,nuevo,0,Colossians,COL,4.000000,letter,,
51,bible,52,1 Tesalonicenses,nuevo,0,1 Thessalonians,1TH,5.000000,letter,,
52,bible,53,2 Tesalonicenses,nuevo,0,2 Thessalonians,2TH,3.000000,letter,,
53,bible,54,1 Timoteo,nuevo,1,1 Timothy,1TI,6.000000,letter,24.5567,39.7785
54,bible,55,2 Timoteo,nuevo,1,2 Timothy,2TI,4.000000,letter,27.4324,38.8303
55,bible,56,Tito,nuevo,1,Titus,TIT,3.000000,letter,24.8093,35.2401
56,bible,57,Filemón,nuevo,1,Philemon,PHM,1.000000,letter,NaN,NaN
57,bible,58,Hebreos,nuevo,1,Hebrews,HEB,13.000000,letter,31.6285,30.469
58,bible,59,Santiago,nuevo,1,James,JAM,5.000000,letter,NaN,NaN
59,bible,60,1 Pedro,nuevo,1,1 Peter,1PE,5.000000,letter,39.2791,36.0485
60,bible,61,2 Pedro,nuevo,1,2 Peter,2PE,3.000000,letter,NaN,NaN
61,bible,62,1 Juan,nuevo,1,1 John,1JO,5.000000,letter,NaN,NaN
62,bible,63,2 Juan,nuevo,1,2 John,2JO,1.000000,letter,NaN,NaN
63,bible,64,3 Juan,nuevo,1,3 John,3JO,1.000000,letter,NaN,NaN
64,bible,65,Judas,nuevo,1,Jude,JUD,1.000000,letter,30.8025,26.8206
65,bible,66,Apocalipsis,nuevo,1,Revelation,REV,22.000000,apocalyptic,33.3589,34.9748
66,,,,,66,,,1189.000000,,,
67,,,,total,51,,,925.000000,,,
68,,,,proportion,0.772727,,,0.777965,,,
69,,,,total falta,14,,,392.000000,,,

In [15]:
books.to_excel(wdir+"documentation/books_2.xlsx", encoding="utf-8")